FROM node:16 AS builder

WORKDIR /app

COPY package*.json .

RUN npm install

RUN npm install -g typescript

COPY . .

RUN npm run build

FROM gcr.io/distroless/nodejs16

WORKDIR /usr/app

COPY package*.json  ./
COPY .env .
RUN apt-get update && apt-get install npm
RUN npm install --production


COPY --from=builder /app/dist ./dist

COPY ./prisma ./dist/src/database

WORKDIR /usr/app/dist/src/database

RUN npx prisma generate

WORKDIR /usr/app

EXPOSE 3004

CMD [ "node", "./dist/src/main.js" ]

#CMD [ "tail","-f" "/dev/null" ]